export default {
  SELECT_CATEGORY: 'SELECT_CATEGORY',
  SELECT_SUBCATEGORY: 'SELECT_SUBCATEGORY',
  SELECT_ITEMTYPE: 'SELECT_ITEMTYPE',
  SELECT_TIER: 'SELECT_TIER',
  SELECT_ENCHANTMENT: 'SELECT_ENCHANTMENT',
  SELECT_EQUIPMENTITEM: 'SELECT_EQUIPMENTITEM',
  SELECT_QUANTITY: 'SELECT_QUANTITY',
  SELECT_TAX: 'SELECT_TAX',
  SELECT_RETURNRATE: 'SELECT_RETURNRATE',
  SELECT_FOCUSRETURNRATE: 'SELECT_FOCUSRETURNRATE'
};
